[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements_simple.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python main_simple.py" 