[build]
builder = "nixpacks"

[deploy]
startCommand = "python main_simple.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
HOST = "0.0.0.0"
PORT = "8000" 