services:
  - type: web
    name: autoresum-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
